name: pocket_champs_clone
description: A simple Pocket Champs style game
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true